baseURL = "https://blog.kubosho.com"
languageCode = "ja-JP"
title = "wkr."
theme = "wkr"
disqusShortname = "blog-kubosho"

[mediaTypes]
  [mediaTypes."application/javascript"]
    suffix = "mjs"

[outputFormats]
  [outputFormats.RSS]
    baseName = "feed"

[params]
ga = "UA-25380313-10"
themecolor = "#003760"
twitter = "kubosho_"
