baseURL = "https://kubosho.github.io/blog"
languageCode = "ja-JP"
title = "wkr."
theme = "wkr"
disqusShortname = "blog-kubosho"

[mediaTypes]
  [mediaTypes."application/javascript"]
    suffix = "mjs"

[params]
twitter = "kubosho_"
