version: '3.3'

services:
  reverse_proxy:
    image: kubosho/blog_reverse_proxy
    volumes:
      - ${PWD}/nginx:/blog/nginx
    ports:
      - "80:80"
      - "443:443"
    container_name: reverse_proxy
    depends_on:
      - backend

  backend:
    image: kubosho/blog_backend
    volumes:
      - ${PWD}:/blog
    ports:
      - "8080:8080"
      # for inspector
      - "9229:9229"
    container_name: backend
