version: 2.1

###########################################
# Constants
###########################################
workspace_root: &workspace_root /tmp/workspace

node_modules_dir: &node_modules_dir node_modules/

defaults: &defaults
    working_directory: *workspace_root

###########################################
# Executor Definitions
###########################################
executors:
    build_executor:
        <<: *defaults
        docker:
            - image: circleci/node:11.6.0

###########################################
# Commands Definitions
###########################################
commands:
    # Observability Commands
    show_yarn_version:
        steps:
            - run: yarn -v

###########################################
# Job Definitions
###########################################
jobs:
    prepare:
        executor: build_executor
        steps:
            - checkout
            - show_yarn_version
            - run:
                  name: Install dependencies
                  command: make init -j
            - persist_to_workspace:
                  root: *workspace_root
                  paths:
                      - *node_modules_dir

    build:
        executor: build_executor
        steps:
            - checkout
            - attach_workspace:
                  at: *workspace_root
            - run:
                  name: Build
                  command: make build -j

    test:
        executor: build_executor
        steps:
            - checkout
            - attach_workspace:
                  at: *workspace_root
            - run:
                  name: Lint sources
                  command: make lint -j
            - run:
                  name: Check formatted sources
                  command: make check_format -j

###########################################
# Workflow Definitions
###########################################
workflows:
    version: 2
    ci_flow:
        jobs:
            - prepare
            - build:
                  requires:
                      - prepare
            - test:
                  requires:
                      - prepare
