# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout

      - run:
          name: Install Hugo
          command: |
            curl -LO https://github.com/gohugoio/hugo/releases/download/v0.40.2/hugo_0.40.2_Linux-64bit.tar.gz
            mkdir hugo && tar xvzf hugo_0.40.2_Linux-64bit.tar.gz -C hugo
      - run:
          name: Generate public files
          command: ./hugo/hugo
      - run:
          name: Copy public files in current directory
          command: |
            cp -r ./public/* .
            rm -rf pcss/
      - persist_to_workspace:
          root: .
          paths:
            - "./*"

  deploy:
    docker:
      - image: circleci/golang:1.9

    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "b3:f5:3c:75:d4:ec:44:9a:8a:14:3b:88:3f:ed:cc:e7"
      - run:
          name: Workaround for CircleCI
          command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Set Git user data
          command: |
            git config --global user.email "ta2@o2p.jp"
            git config --global user.name "Shota Kubota"
      - run: git add .
      - run: git commit -m "[ci skip] published of Hugo generated files"
      - run:
          name: Change Git branch
          command: git checkout gh-pages
      - run:
          name: Push to gh-pages branch
          command: git push origin gh-pages
      - run:
          name: Reset master branch
          command: |
            git checkout master
            git reset --hard origin/master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
